name: Automate Weather Data

on:
  schedule:
    - cron: '0 11 * * *' # Runs daily at 10am UTC
  workflow_dispatch:

jobs:
  update-weather-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Configure Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Run weather.sh
        run: |
          chmod +x weather.sh
          ./weather.sh
      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Update weather data [GitHub Actions]"
          git push
